### ISSUE TITLE
Build failed on Jetson Nano R32.4.2

### ISSUE THREAD

**Issue by qubitqualia** [mdegans/nano_build_opencv#36]
![image](https://user-images.githubusercontent.com/39470632/87224361-9ef7dc80-c352-11ea-880c-b64449032073.png)

**Comment by mdegans** [comment]
Appears same issue as #35 

Problem can be solved by running
```
build_opencv.sh master
```

I will leave this open since a lot of people will likely have this problem soon. If people think I should change the default branch to master, upvote this comment.

**Comment by mdegans** [comment]
@qubitqualia 
I'm going to close this since OpenCV 4.4.0 has been tagged upstream and builds. I've set it as the default version so `build_opencv.sh` should be all that's required. If you need any more help on this issue, feel free to re-open or comment on #35
