### ISSUE TITLE
build failed, "repository no longer signed"

### ISSUE THREAD

**Issue by GOBish** [mdegans/nano_build_opencv#39]
I have used your excellent script in the past successfully, but it seems something changed recently that is giving me the following error:

```
Reading package lists... Done                      
E: Failed to fetch http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/dists/bionic/InRelease  403  Forbidden [IP: 52.218.53.57 80]
E: The repository 'http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
Edit to add : Jetpack 4.4
tried ./build_opencv.sh master, same result.

**Comment by mdegans** [comment]
That would seem to be a problem with the with intel RealSense repository configuration. You should be able to fix that by registering the public key as shown in the setup docs here:

https://github.com/IntelRealSense/librealsense/blob/development/doc/distribution_linux.md#installing-the-packages

Feel free to re-open if that doesn't fix it, or you can google the error and there are a few issues about it on the realsense repo.

**Comment by GOBish** [comment]
Thanks, got it to work
